server:
  port: 0  # Each service gets a random port unless overridden

spring:
  application:
    name: configserver
  profiles:
    active: prod
  cloud:
    config:
      fail-fast: true
      retry:
        maxAttempts: 6
        initialInterval: 2000
        multiplier: 1.5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
